# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-14 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import month.models
import resume_builder.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('graduation', month.models.MonthField(help_text='Year-month of graduation', verbose_name='Month Value')),
                ('start', month.models.MonthField(help_text='Year-month of start', verbose_name='Month Value')),
                ('text', models.TextField(help_text='Please enter few words regarding the education in the institute.')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('start_date', month.models.MonthField(help_text='Year-month of start', verbose_name='Month Value')),
                ('end_date', month.models.MonthField(help_text='Year-month of end', null=True, verbose_name='Month Value')),
                ('still_working', models.BooleanField(default=False)),
                ('text', models.TextField(help_text='Please enter few words regarding the work in the institute.')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(help_text='Please enter few words regarding the project.')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='Please enter few words which would best describe you.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', resume_builder.fields.MinMaxRangeField(default=3)),
                ('text', models.TextField(blank=True, help_text='Please enter few words regarding the skill.', null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Resume')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Resume'),
        ),
        migrations.AddField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Resume'),
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Resume'),
        ),
    ]
