# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-11 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=25, verbose_name='Type of Transaction')),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Direct Deposit', 'Direct Deposit'), ('Other', 'Other')], default='Credit Card', max_length=25, verbose_name='Method of Transaction')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('category', models.CharField(default='Others', max_length=100, verbose_name='Category')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
